import type { NextComponentType, NextPage } from 'next'
import Head from 'next/head'
import { useCallback, useState } from 'react';
import Navbar from './navbar';


const Wrapper = (props: {name?: string, navSticky?: boolean, children: any, navBg?: boolean}) => {
	const [scrolled, setScrolled] = useState(false)
	const onScroll = (e: any) => {
		 setScrolled(e.target.scrollTop > 1 ? true : false);
	};
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<div onScroll={onScroll} className="min-h-screen flex flex-col">
				<Navbar sticky={props.navSticky} bg={props.navBg} scrolled={scrolled} />
				<div className="flex-1">
					{props.children}
				</div>
			</div>
      </>
  )
}

export default Wrapper
